### ISSUE TITLE
warning issue when using ciftify package: h5py future warning

### ISSUE THREAD

**Issue by zhangyu2ustc** [SIMEXP/fmri_predict#11]
/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

Solution:
fixed the problem by:
    ###upgrade the package
    pip install h5py==2.8.0rc1
as listed in the website: 
   https://github.com/h5py/h5py/issues/961

**Comment by zhangyu2ustc** [comment]
problems during package installation using pip:

Traceback (most recent call last):
  File "/home/yu/tensorflow-py3.6/bin/pip3", line 7, in <module>
    from pip._internal import main
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 23, in <module>
    from pip._internal.index import PackageFinder
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/pip/_internal/index.py", line 15, in <module>
    from pip._vendor.distlib.compat import unescape
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/pip/_vendor/distlib/compat.py", line 85, in <module>
    from html.parser import HTMLParser
ModuleNotFoundError: No module named 'html.parser'; 'html' is not a package


Reason:
Ciftify has a html.py file which has conflicting issues with the pip package
rename it:
mv /home/yu/tensorflow-py3.6/lib/python3.6/site-packages/ciftify/html.py /home/yu/tensorflow-py3.6/lib/python3.6/site-packages/ciftify/html_ciftify.py

might cause issues in the future
